import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Recommendation } from '../types';

export async function generateWardReport(
    mapElementId: string,
    wardName: string,
    avgScore: number,
    starRating: number,
    population: number,
    recommendations: Recommendation[]
) {
    // 1. Capture Map Screenshot
    const mapElement = document.getElementById(mapElementId);
    let mapImage = '';
    if (mapElement) {
        const canvas = await html2canvas(mapElement, { useCORS: true, logging: false });
        mapImage = canvas.toDataURL('image/png');
    }

    // 2. Initialize PDF
    const doc = new jsPDF('p', 'mm', 'a4');
    const margin = 20;
    let yPos = margin;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59); // slate-800
    doc.text(`ServiceMap Policy Report`, margin, yPos);

    doc.setFontSize(14);
    doc.setTextColor(100, 116, 139); // slate-500
    yPos += 8;
    doc.text(`Neighborhood: ${wardName}`, margin, yPos);

    yPos += 15;

    // Stats summary
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text(`Average Accessibility Score: ${avgScore} / 100`, margin, yPos);
    yPos += 7;
    doc.text(`Locality Rating: ${'⭐'.repeat(starRating)}`, margin, yPos);
    yPos += 7;
    doc.text(`Estimated Population: ${population.toLocaleString()}`, margin, yPos);

    yPos += 15;

    // Map Image
    if (mapImage) {
        doc.text(`Area Snapshot`, margin, yPos);
        yPos += 5;
        // adding image maintaining aspect ratio
        const imgProps = doc.getImageProperties(mapImage);
        const pdfWidth = doc.internal.pageSize.getWidth() - 2 * margin;
        const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
        doc.addImage(mapImage, 'PNG', margin, yPos, pdfWidth, pdfHeight);
        yPos += pdfHeight + 15;
    }

    // Top Recommendation
    if (recommendations && recommendations.length > 0) {
        const topRec = recommendations[0];
        doc.setFontSize(14);
        doc.setTextColor(220, 38, 38); // red-600
        doc.text(`Top Infrastructure Gap`, margin, yPos);

        yPos += 8;
        doc.setFontSize(11);
        doc.setTextColor(71, 85, 105); // slate-600
        doc.text(`Missing Service: ${topRec.missing_service.replace('_', ' ').toUpperCase()}`, margin, yPos);
        yPos += 6;
        doc.text(`Recommendation: ${topRec.recommendation_text}`, margin, yPos);
        yPos += 6;
        doc.text(`Priority / Severity: ${topRec.severity}`, margin, yPos);
    } else {
        doc.setFontSize(12);
        doc.text(`No critical infrastructure gaps detected.`, margin, yPos);
    }

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`Generated by ServiceMap AI Platform • ${new Date().toLocaleDateString()}`, margin, doc.internal.pageSize.getHeight() - 15);

    // Download
    doc.save(`${wardName.replace(/\s+/g, '_')}_Accessibility_Report.pdf`);
}
