# fetchOSMData.py
# Reference implementation for fetching OpenStreetMap POIs via Overpass API
# Note: For hackathon stability, public/data/*.json are pre-generated by generateData.mjs

import json
import requests
import os

BBOX = "12.92,77.55,13.02,77.65"
OVERPASS_URL = "http://overpass-api.de/api/interpreter"

def build_query(bbox):
    return f"""
    [out:json][timeout:25];
    (
      node["amenity"="hospital"]({bbox});
      node["amenity"="school"]({bbox});
      node["highway"="bus_stop"]({bbox});
      node["amenity"="police"]({bbox});
      node["amenity"="fire_station"]({bbox});
    );
    out body;
    """

def fetch_data():
    query = build_query(BBOX)
    response = requests.post(OVERPASS_URL, data={'data': query})
    if response.status_code == 200:
        data = response.json()
        facilities = []
        for element in data.get('elements', []):
            tags = element.get('tags', {})
            fac_type = tags.get('amenity') or tags.get('highway')
            facilities.append({
                "id": str(element['id']),
                "type": fac_type,
                "name": tags.get('name', f"{fac_type} {element['id']}"),
                "lat": element['lat'],
                "lng": element['lon']
            })
        
        out_path = os.path.join(os.path.dirname(__file__), '../public/data/facilities.json')
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, 'w') as f:
            json.dump(facilities, f, indent=2)
        print(f"Generated {len(facilities)} facilities to {out_path}")
    else:
        print("Error fetching OSM data")

if __name__ == "__main__":
    print("This script is a reference. JSON is preloaded via JS script to avoid API rate limits.")
